version: "3.9"
services:
  agent:
    build: .
    image: agent-001:latest
    ports: ["9000:9000"]
    environment:
      TARGETS: >-
        http://localhost:8000/health,
        http://localhost:5173/health
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
    restart: unless-stopped