apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecosystem-monitor
  labels:
    app: ecosystem-monitor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ecosystem-monitor
  template:
    metadata:
      labels:
        app: ecosystem-monitor
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: agent
        image: agent-001:latest
        ports:
        - containerPort: 9000
          name: http
        env:
        - name: PORT
          value: "9000"
        - name: SERVICES_JSON
          value: '[{"name":"api","url":"http://api-service:8080/health"},{"name":"db","url":"http://postgres:5432/health"}]'
        - name: TIMEOUT_SEC
          value: "5.0"
        - name: GIT_SHA
          value: "k8s-deploy"
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
        livenessProbe:
          httpGet:
            path: /live
            port: 9000
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 9000
          initialDelaySeconds: 3
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 2
        startupProbe:
          httpGet:
            path: /live
            port: 9000
          initialDelaySeconds: 1
          periodSeconds: 1
          timeoutSeconds: 1
          failureThreshold: 10
---
apiVersion: v1
kind: Service
metadata:
  name: ecosystem-monitor
  labels:
    app: ecosystem-monitor
spec:
  selector:
    app: ecosystem-monitor
  ports:
  - name: http
    port: 80
    targetPort: 9000
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    scrape_configs:
    - job_name: 'ecosystem-monitor'
      scrape_interval: 15s
      static_configs:
      - targets: ['ecosystem-monitor:80']
      metrics_path: '/metrics'